/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-05-05T07:37:10.859Z[GMT]")
@Api(value = "register", description = "the register API")
public interface RegisterApi {

    @ApiOperation(value = "Register new user", nickname = "register", notes = "Register user to the system", tags={ "employee","customer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Register complete"),
        @ApiResponse(code = 400, message = "Register failed") })
    @RequestMapping(value = "/register",
        consumes = { "application/x-www-form-urlencoded" },
        method = RequestMethod.POST)
    ResponseEntity<Void> register(@ApiParam(value = "") @RequestParam(value="username", required=false)  String username
,@ApiParam(value = "") @RequestParam(value="password", required=false)  String password
,@ApiParam(value = "") @RequestParam(value="email", required=false)  String email
,@ApiParam(value = "") @RequestParam(value="birthdate", required=false)  String birthdate
,@ApiParam(value = "") @RequestParam(value="bsn", required=false)  Integer bsn
);

}
